version: "3.9"

services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 10

  web:
    build: .
    command: >
      sh -c "python manage.py migrate &&
             daphne -b 0.0.0.0 -p 8000 config.asgi:application"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      DATABASE_URL: postgis://postgres:postgres@host.docker.internal:5432/eta_eats_v2
      REDIS_URL: redis://redis:6379/0
    depends_on:
      redis:
        condition: service_healthy

  celery:
    build: .
    command: celery -A config worker -l info
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      DATABASE_URL: postgis://postgres:postgres@host.docker.internal:5432/eta_eats_v2
      REDIS_URL: redis://redis:6379/0
    depends_on:
      redis:
        condition: service_healthy

  celery-beat:
    build: .
    command: celery -A config beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      DATABASE_URL: postgis://postgres:postgres@host.docker.internal:5432/eta_eats_v2
      REDIS_URL: redis://redis:6379/0
    depends_on:
      redis:
        condition: service_healthy
