# Generated by Django 4.2.30 on 2026-04-21 18:09

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bus_name', models.CharField(max_length=200)),
                ('number_plate', models.CharField(max_length=20, unique=True)),
                ('qr_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('qr_image_url', models.CharField(blank=True, max_length=500)),
                ('total_seats', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('current_location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('last_gps_update', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Bus',
                'verbose_name_plural': 'Buses',
            },
        ),
        migrations.CreateModel(
            name='BusOperator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company_name', models.CharField(max_length=200)),
                ('contact_name', models.CharField(blank=True, max_length=200)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Bus Operator',
                'verbose_name_plural': 'Bus Operators',
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('origin_city', models.CharField(max_length=100)),
                ('destination_city', models.CharField(max_length=100)),
                ('distance_km', models.PositiveIntegerField()),
                ('estimated_duration_hours', models.DecimalField(decimal_places=1, max_digits=4)),
            ],
            options={
                'verbose_name': 'Route',
                'verbose_name_plural': 'Routes',
                'indexes': [models.Index(fields=['origin_city', 'destination_city'], name='fleet_route_origin__374bb9_idx')],
            },
        ),
        migrations.CreateModel(
            name='BusRestaurantAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bus_assignments_made', to=settings.AUTH_USER_MODEL)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_assignments', to='fleet.bus')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bus_assignments', to='restaurants.restaurant')),
            ],
            options={
                'verbose_name': 'Bus-Restaurant Assignment',
                'verbose_name_plural': 'Bus-Restaurant Assignments',
            },
        ),
        migrations.CreateModel(
            name='BusGPSLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gps_logs', to='fleet.bus')),
            ],
            options={
                'verbose_name': 'Bus GPS Log',
                'verbose_name_plural': 'Bus GPS Logs',
            },
        ),
        migrations.AddField(
            model_name='bus',
            name='operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='buses', to='fleet.busoperator'),
        ),
        migrations.AddField(
            model_name='bus',
            name='route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buses', to='fleet.route'),
        ),
        migrations.AddConstraint(
            model_name='busrestaurantassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('bus',), name='unique_active_bus_assignment'),
        ),
        migrations.AddIndex(
            model_name='busgpslog',
            index=models.Index(fields=['bus', '-recorded_at'], name='fleet_busgp_bus_id_0536f0_idx'),
        ),
        migrations.AddIndex(
            model_name='bus',
            index=models.Index(fields=['operator', 'is_active'], name='fleet_bus_operato_6a0400_idx'),
        ),
        migrations.AddIndex(
            model_name='bus',
            index=models.Index(fields=['qr_token'], name='fleet_bus_qr_toke_e6b8ce_idx'),
        ),
    ]
