# Generated by Django 5.2.13 on 2026-04-24 13:33

import apps.fleet.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='qr_token',
            field=models.CharField(default=apps.fleet.models.generate_qr_token, editable=False, max_length=6, unique=True),
        ),
    ]
