import type { Config } from 'tailwindcss'

const config: Config = {
  content: ['./src/**/*.{js,ts,jsx,tsx,mdx}'],
  theme: {
    extend: {
      colors: {
        bg:        'var(--bg)',
        surface:   'var(--surface)',
        surface2:  'var(--surface-2)',
        primary:   'var(--primary)',
        'primary-soft': 'var(--primary-soft)',
        'primary-dark': 'var(--primary-dark)',
        accent: {
          'powder-blue': 'var(--accent-powder-blue)',
          'soft-cream': 'var(--accent-soft-cream)',
          peach: 'var(--accent-peach)',
          'muted-mint': 'var(--accent-muted-mint)',
        },
        gray: {
          50: 'var(--gray-50)',
          100: 'var(--gray-100)',
          150: 'var(--gray-150)',
          200: 'var(--gray-200)',
          300: 'var(--gray-300)',
          400: 'var(--gray-400)',
          500: 'var(--gray-500)',
          600: 'var(--gray-600)',
          700: 'var(--gray-700)',
          800: 'var(--gray-800)',
          900: 'var(--gray-900)',
        },
        border:    'var(--border)',
        'border-strong': 'var(--border-strong)',
        'text-primary':   'var(--text-primary)',
        'text-secondary': 'var(--text-secondary)',
        'text-muted':     'var(--text-muted)',
        success:   'var(--success)',
        'success-bg': 'var(--success-bg)',
        warning:   'var(--warning)',
        'warning-bg': 'var(--warning-bg)',
        error:     'var(--error)',
        'error-bg': 'var(--error-bg)',
        info:      'var(--info)',
        'info-bg': 'var(--info-bg)',
      },
      borderRadius: {
        sm: 'var(--radius-sm)',
        md: 'var(--radius-md)',
        lg: 'var(--radius-lg)',
        xl: 'var(--radius-xl)',
        card: 'var(--radius-card)',
        pill: 'var(--radius-pill)',
      },
      fontFamily: {
        sans: ['Satoshi', 'General Sans', 'Neue Montreal', 'Inter', 'sans-serif'],
      },
      spacing: {
        1: '4px',
        2: '8px',
        3: '12px',
        4: '16px',
        5: '20px',
        6: '24px',
        8: '32px',
        10: '40px',
        12: '48px',
        16: '64px',
      },
      boxShadow: {
        e1: '0 1px 2px rgba(17, 17, 17, 0.04)',
        e2: '0 6px 18px rgba(17, 17, 17, 0.06)',
        cta: '0 8px 24px rgba(17, 17, 17, 0.10)',
        modal: '0 14px 36px rgba(17, 17, 17, 0.12)',
      },
    },
  },
  plugins: [],
}

export default config
